[package]
name = "parquet-probe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
color-eyre = "0.6.3"
parquet = "53.1.0"
ratatui = "0.29.0"
